### ISSUE TITLE
R Codes miss somewhere

### ISSUE THREAD

**Issue by JywangTest** [bnaras/cvxr_docs#1]
Thanks for your work in CVXR package. There seems a little problem in codes appear in the on-line introduction of CVXR (https://cvxr.rbind.io/post/examples/cvxr_gentle-intro/)
Maybe you need check in your path: cvxr_docs/content/post/examples/cvxr_gentle_intro.Rmd line 316.
I think the echo should be TRUE to make the process of data generation appear

**Comment by bnaras** [comment]
Just saw this. Thank you. Fixed.
