### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by jacobbien** [bnaras/cvxr_docs#23]
I believe [this page](https://github.com/bnaras/cvxr_docs/blob/324b5c437e86a44e0f91e61d44c671f9bcfd37e8/content/functions_data/index.rst) has a typo.  In particular, in the function reference table, I think `quad_over_lin`'s domain should show X as an m-by-n matrix.

**Comment by anqif** [comment]
Fixed in commit [187d23d](https://github.com/bnaras/cvxr_docs/commit/187d23d8324041b2670b588868ca34fce4f3d4cd)
