### ISSUE TITLE
MOSEK related links need to be updated/fixed

### ISSUE THREAD

**Issue by Utkarsh-Detha** [bnaras/cvxr_docs#25]
Thank you for supporting MOSEK in CVXR. I noticed the following links in the documentation were either old or not pointing to where they should be:

1. The Rmosek link on the homepage (in the table) points to the Rmosek-meta package on CRAN. As the CRAN package is simply an installer for Rmosek, it should instead point to Rmosek documentation: https://docs.mosek.com/latest/rmosek/index.html
2. The Rmosek link in the table on [using other solvers page](https://cvxr.rbind.io/cvxr_examples/cvxr_using-other-solvers/) is wrong. It should also be pointing to the aforementioned [Rmosek documentation](https://docs.mosek.com/latest/rmosek/index.html)
3. Under the "Installing MOSEK" section on the on [using other solvers page](https://cvxr.rbind.io/cvxr_examples/cvxr_using-other-solvers/), there is a link to Rmosek documentation that points to older (v 9.1) documentation. It would be better if it instead pointed to the "latest" documentation, that is to: https://docs.mosek.com/latest/rmosek/index.html

I just opened an issue because I wasn't sure if I should make PR. Let me know if you would rather have me make a PR with the changes implemented. Thank you.

**Comment by anqif** [comment]
Fixed in d4d05b937fc708de5808b8999f8377c3eb6cadf6
